from __future__ import annotations

import argparse
import json
import math
import subprocess
import sys
import time
from pathlib import Path
from typing import List

from il_data_tools.domain_randomization import PRESETS


DEFAULT_PRESET_CYCLE = [
    "baseline",
    "visual_light",
    "visual_dark",
    "sensor",
    "dynamics",
    "mixed",
]

GAZEBO_PROCESS_PATTERN = r"^gz sim"


def cleanup_gazebo_children() -> None:
    """Remove Gazebo children that survive a completed or interrupted launch."""
    for signal_name, wait_sec in (
        ("TERM", 1.0),
        ("KILL", 0.5),
        ("KILL", 0.5),
    ):
        subprocess.run(
            ["pkill", f"-{signal_name}", "-f", GAZEBO_PROCESS_PATTERN],
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        if wait_sec:
            time.sleep(wait_sec)


def _parse_presets(value: str) -> List[str]:
    presets = [part.strip() for part in value.split(",") if part.strip()]
    unknown = sorted(set(presets) - set(PRESETS))
    if not presets or unknown:
        raise argparse.ArgumentTypeError(
            f"invalid preset cycle; unknown={unknown}, valid={sorted(PRESETS)}"
        )
    return presets


def _project_root(value: str) -> Path:
    path = Path(value).expanduser().resolve()
    expected = path / "worlds" / "kookmin_xycar_track_final.sdf"
    if not expected.is_file():
        raise argparse.ArgumentTypeError(f"final world not found below {path}")
    return path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Collect multiple independently randomized Gazebo IL sessions."
    )
    parser.add_argument(
        "--project-root",
        type=_project_root,
        default=str(Path.cwd()),
    )
    parser.add_argument(
        "--output-root",
        default="",
        help="Dataset root; defaults to PROJECT_ROOT/datasets/il.",
    )
    parser.add_argument(
        "--generated-output-dir",
        default="",
        help="Generated SDF/manifest root; defaults to PROJECT_ROOT/generated/domain_randomization.",
    )
    parser.add_argument("--total-samples", type=int, default=50_000)
    parser.add_argument("--batch-samples", type=int, default=5_000)
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument(
        "--presets",
        type=_parse_presets,
        default=DEFAULT_PRESET_CYCLE,
        help="Comma-separated preset cycle.",
    )
    parser.add_argument(
        "--show-gui-first",
        action="store_true",
        help="Show Gazebo/RViz for the first batch only.",
    )
    parser.add_argument("--scenario-interval-sec", type=float, default=24.0)
    parser.add_argument("--recovery-hold-sec", type=float, default=9.0)
    parser.add_argument(
        "--canonical-input",
        action="store_true",
        help="Store /perception/canonical_road_image as lossless PNG.",
    )
    parser.add_argument(
        "--canonical-artifacts",
        action="store_true",
        help=(
            "Store a label-preserving canonical stream with short centerline "
            "jumps, white-boundary bends, and line dropouts."
        ),
    )
    parser.add_argument(
        "--canonical-artifact-mode",
        choices=("real_visibility", "legacy"),
        default="real_visibility",
        help="Use geometry-preserving real visibility loss or legacy synthetic bends.",
    )
    parser.add_argument(
        "--real-reference-profile",
        default="",
        help="JSON generated by scripts/build_real_reference_profile.py.",
    )
    parser.add_argument("--max-save-rate-hz", type=float, default=10.0)
    parser.add_argument(
        "--lane-offset-from-yellow-m",
        type=float,
        default=0.05,
        help="Nominal rule path used as the center of recovery perturbations.",
    )
    return parser


def visibility_target(profile_path: str) -> dict[str, float]:
    target = {
        "white_both_probability": 0.462,
        "white_one_probability": 0.512,
        "white_none_probability": 0.026,
        "yellow_visible_probability": 0.571,
    }
    if not profile_path:
        return target
    path = Path(profile_path).expanduser().resolve()
    with path.open(encoding="utf-8") as handle:
        document = json.load(handle)
    configured = document.get("recommended_sim_visibility", {})
    for key in target:
        if key in configured:
            target[key] = float(configured[key])
    white_total = sum(
        target[key]
        for key in (
            "white_both_probability",
            "white_one_probability",
            "white_none_probability",
        )
    )
    if white_total <= 0.0 or any(value < 0.0 for value in target.values()):
        raise SystemExit(f"invalid real reference visibility profile: {path}")
    for key in (
        "white_both_probability",
        "white_one_probability",
        "white_none_probability",
    ):
        target[key] /= white_total
    if not 0.0 <= target["yellow_visible_probability"] <= 1.0:
        raise SystemExit(f"invalid yellow probability in: {path}")
    return target


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    if args.total_samples <= 0 or args.batch_samples <= 0:
        raise SystemExit("sample counts must be positive")
    session_count = int(math.ceil(args.total_samples / args.batch_samples))
    remaining = args.total_samples
    output_root = (
        Path(args.output_root).expanduser().resolve()
        if args.output_root
        else args.project_root
        / "datasets"
        / ("il_canonical" if args.canonical_input else "il")
    )
    generated_output_dir = (
        Path(args.generated_output_dir).expanduser().resolve()
        if args.generated_output_dir
        else args.project_root / "generated" / "domain_randomization"
    )
    visibility = visibility_target(args.real_reference_profile)
    print(
        f"randomized collection: total={args.total_samples}, "
        f"sessions={session_count}, root={args.project_root}"
    )

    cleanup_gazebo_children()
    for index in range(session_count):
        preset = args.presets[index % len(args.presets)]
        seed = args.seed + index
        samples = min(args.batch_samples, remaining)
        representation = "canonical_" if args.canonical_input else ""
        session_name = f"sim_{representation}{preset}_s{seed}"
        show_gui = args.show_gui_first and index == 0
        command = [
            "ros2",
            "launch",
            "il_data_tools",
            "collect_randomized_sim_dataset.launch.py",
            f"project_root:={args.project_root}",
            f"output_root:={output_root}",
            f"generated_output_dir:={generated_output_dir}",
            f"session_name:={session_name}",
            f"max_samples:={samples}",
            f"seed:={seed}",
            f"preset:={preset}",
            f"show_gui:={'true' if show_gui else 'false'}",
            f"scenario_interval_sec:={args.scenario_interval_sec}",
            f"recovery_hold_sec:={args.recovery_hold_sec}",
            f"max_save_rate_hz:={args.max_save_rate_hz}",
            f"lane_offset_from_yellow_m:={args.lane_offset_from_yellow_m}",
            f"canonical_artifact_mode:={args.canonical_artifact_mode}",
            "visibility_white_both_probability:="
            f"{visibility['white_both_probability']}",
            "visibility_white_one_probability:="
            f"{visibility['white_one_probability']}",
            "visibility_white_none_probability:="
            f"{visibility['white_none_probability']}",
            "visibility_yellow_probability:="
            f"{visibility['yellow_visible_probability']}",
        ]
        if args.canonical_input:
            command += [
                "camera_front_topic:="
                + (
                    "/perception/canonical_road_image_augmented"
                    if args.canonical_artifacts
                    else "/perception/canonical_road_image"
                ),
                "image_format:=png",
                "exclude_blank_canonical:=true",
                "canonical_artifacts_enabled:="
                + ("true" if args.canonical_artifacts else "false"),
            ]
        print(
            f"\n[{index + 1}/{session_count}] preset={preset} seed={seed} "
            f"samples={samples} gui={show_gui}"
        )
        try:
            result = subprocess.run(command, check=False)
        except KeyboardInterrupt:
            print("\ncollection interrupted; completed sessions remain on disk")
            return 130
        finally:
            cleanup_gazebo_children()
        if result.returncode != 0:
            print(
                f"session failed with exit code {result.returncode}: {' '.join(command)}",
                file=sys.stderr,
            )
            return result.returncode
        remaining -= samples

    print(f"\ncompleted {args.total_samples} new randomized samples")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
